v2
naoned/google-auth pull request #1
Opened 2018-06-21 09:43 UTC by mcharron

Onyx plugin

2018-06-22 22:33 UTC, Niktux requested changes

2018-06-22 22:33 UTC, Niktux commented on Makefile
> +###############################################################################
committé par erreur ?

2018-06-22 22:33 UTC, Niktux commented on config/google_auth.conf.example
> +google_auth.redirect_route_after_successfull_login:
typo : successful (avec un seul l)

2018-06-22 22:33 UTC, Niktux commented on config/google_auth.conf.example
> +    dev = home
mets seulement : `default = __FIXME__`

2018-06-22 22:33 UTC, Niktux commented on config/google_auth.conf.example
> +    dev = <your_domain_name>
idem

2018-06-22 22:33 UTC, Niktux commented on docker/images/cli/Dockerfile
> +# Contains php and composer : all the stuff to run reprise projects
what ???

2018-06-22 22:33 UTC, Niktux commented on makefiles/whalephant.mk
> +.PHONY: clean-whalephant clean-phpunit-dockerfile
vire les répertoires makefiles et docker

2018-06-22 22:33 UTC, Niktux commented on src/Infrastructure/Clients/Api.php
> +    private function computeConfiguration(array $readConfiguration): array
pas utilisé ? (bug)

2018-06-26 11:42 UTC, lebris commented on src/GoogleAuthServiceProvider.php
> +        $container['google_auth.listeners.alwaysRedirectToLogin'] = function($c) {
type hinting `function(Container $c) {`

2018-06-26 11:42 UTC, lebris commented on src/Infrastructure/Controllers/Controller.php
> +
CS

2018-06-26 11:42 UTC, lebris commented on src/Infrastructure/Controllers/Provider.php
> +
CS

2018-06-26 11:56 UTC, mcharron commented
@lebris c'est fixé

2018-07-05 15:44 UTC, Niktux approved these changes

2018-07-06 21:24 UTC, merged